[workspace]
resolver = "2"
members = [
    "crates/pyromirror-proto",
    "crates/pyrowave-sys",
    "crates/pyromirror-codec",
    "crates/pyromirror-net",
    "crates/pyromirror-capture",
    "crates/pyromirror-audio",
    "crates/pyromirror-server",
    "crates/pyromirror-client",
    "crates/pyromirror-gui",
]

[workspace.package]
version = "0.1.0-beta.3"
edition = "2021"
authors = ["PyroMirror Contributors"]
license = "Apache-2.0"
repository = "https://github.com/caioquirino/pyromirror"

[workspace.dependencies]
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
byteorder = "1.5"
socket2 = "0.5"
crossbeam-channel = "0.5"
sdl3 = "0.20"
thiserror = "1.0"
anyhow = "1.0"
