[package]
name = "pyromirror-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pyromirror"
path = "src/main.rs"

[dependencies]
pyromirror-proto = { path = "../pyromirror-proto" }
eframe = { version = "0.36", default-features = false, features = ["glow", "default_fonts", "wayland", "x11"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = { workspace = true }
env_logger = { workspace = true }

[target.'cfg(windows)'.dependencies]
tray-icon = "0.26"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging"] }

[target.'cfg(target_os = "linux")'.dependencies]
ksni = { version = "0.3", default-features = false, features = ["blocking", "async-io"] }
