[package]
name = "pyromirror-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pyromirror-proto = { path = "../pyromirror-proto" }
pyromirror-net = { path = "../pyromirror-net" }
pyromirror-codec = { path = "../pyromirror-codec" }
pyromirror-capture = { path = "../pyromirror-capture" }
pyromirror-audio = { path = "../pyromirror-audio" }
crossbeam-channel = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }

[build-dependencies]
winresource = "0.1"
